name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        server-impl: ['jetty12-ee10', 'jetty12-ee9', 'jetty11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        id: setup-java-17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with maven, install to m2 so we can use servlet
        run: mvn -B -ntp -U -e install
      - name: Run server and client together
        run: |
            mvn -B -ntp -U -e -pl :${{ matrix.server-impl }} exec:java & \
            tcpdump -C 10 -Z root -i any -U -w tcpdump.pcap & \
            sleep 5; \
            mvn -B -ntp -U -e -pl :client exec:java; \
            sleep 1; \
            kill %1; \
            kill %2; \
            sleep 1;
      - name: Upload tcpdump
        uses: actions/upload-artifact@v4
        with:
          path: tcpdump.pcap
